//! OpenCode 适配器：OpenCode 不用 command hooks，而是 JS 插件体系。
//! 我们生成一个插件文件，并把其绝对路径注册到 ~/.config/opencode/opencode.json
//! 的 plugin 数组。插件内部直接 POST 统一格式事件到本地 daemon。
//!
//! 事件挂载方式（重要）：OpenCode 的插件对象由通用 `event` 回调接收事件流
//! （`event: async ({ event }) => { if (event.type === "session.idle") ... }`），
//! 官方文档的示例即此形态。旧版本这里把 `"session.idle"` 当作 hook 键直接挂，
//! 与官方 API 不符、不会被调用，因此改为 `event` 回调 + 事件名分发。
//! 同时保留逐事件键，兼容部分版本可能存在的直接挂载。
//!
//! 心跳（「思考中/执行工具」的数据源）：回合开始/结束走 `session.status`
//! （busy/retry/idle，官方 SDK 实证），工具执行走 `message.part.updated` 里
//! `part.type === "tool"` 的部件（`part.tool` 是工具名、`state.status` 是
//! pending/running/completed/error）。没有心跳的 agent 会话进不了「运行中」表——
//! 旧版插件只映射终态/打断，结果就是「跑的时候毫无表现，完成才弹一条通知」。
//! 归一在插件 JS 内完成（本 adapter 的 normalize 不参与）。
//!
//! 注意事件名以官方 SDK 的 types.gen.ts 为准：旧版映射里的 `permission.asked`
//! 并不存在（实际是 `permission.updated`），`question.asked` 在 opencode 里
//! 根本没有对应事件，均已修正/移除。
//!
//! 中止检测（手动 Esc 取消回合）：官方事件页没有 abort 语义文档，但社区插件
//! （opencode-auto-resume）实证 Esc 取消走 `session.error` 且错误名为
//! `MessageAbortedError`——归一成 `run_aborted`（不亮终止色不通知），并压制
//! 其后 10s 内的 `session.idle`（否则中止紧跟一条绿色「完成」，谎报跑完）。
//! 判定是防御式字符串匹配：匹配不上回落 `run_failed`，最坏情况 = 无中止检测的旧行为。
//!
//! 会话元数据：运行中的事件只带 sessionID，cwd 唯一来源是 session.created/updated
//! 的 `info.directory`，子代理标记唯一来源是 `info.parentID`——插件内按 sessionID
//! 记下来（有界缓存），否则终态/等待通知没有项目名、子代理会话刷屏。

use crate::jsonio;
use crate::{HookAdapter, InstallCtx, RegisterCtx, VerifyReport};
use bark_core::{AgentKind, EventKind, NormalizedEvent};
use serde_json::{json, Value};
use std::path::{Path, PathBuf};

pub struct OpenCodeAdapter;

fn home() -> PathBuf {
    dirs::home_dir().unwrap_or_else(|| PathBuf::from("."))
}

fn plugin_file() -> PathBuf {
    // 与主配置同目录：<config_dir>/agent-bark/opencode-plugin.js
    dirs::config_dir()
        .unwrap_or_else(home)
        .join("agent-bark")
        .join("opencode-plugin.js")
}

/// 当前插件路径的正斜杠形式（写入 opencode.json 的登记形态）
fn plugin_path_str() -> String {
    plugin_file().to_string_lossy().replace('\\', "/")
}

fn config_file() -> PathBuf {
    home().join(".config").join("opencode").join("opencode.json")
}

fn plugin_js(port: u16, token: &str) -> String {
    // 纵深防御：token 经 serde_json 序列化为带转义的 JS 双引号字符串字面量，
    // 即使未来 token 含引号/反斜杠/控制字符也不会破坏生成的 JS
    // （serde_json 的字符串转义规则是 JS 字符串字面量的安全子集）。
    let token_js = serde_json::to_string(token).unwrap_or_else(|_| "\"\"".into());
    format!(
        r#"// Generated by agent-bark. Do not edit; re-register from agent-bark UI to refresh.
// 该文件含本地事件服务的 token（用于向 127.0.0.1 的 daemon 鉴权），请勿提交到版本库。
const ENDPOINT = "http://127.0.0.1:{port}/event";
const TOKEN = {token_js};

// agent 事件名 → 统一事件类型。只列官方 SDK types.gen.ts 里真实存在的事件名：
// 旧版的 permission.asked / question.asked 并不存在（权限打断走 permission.updated）
const KIND_MAP = {{
  "session.created": "session_start",
  "permission.updated": "permission_required",
}};

/** 单次 POST 的超时（ms）：daemon 是本地进程，正常毫秒级返回。
 * 没有超时的话，daemon 端口被「只接受连接不响应」的进程占用/死锁时插件回调
 * 会永久挂起——OpenCode 若串行 await 插件回调，会拖住事件管线乃至回合收尾
 * （§1.10；与 dsh 生成插件同款防御，常量命名也一致）。 */
const POST_TIMEOUT_MS = 2000;

async function post(type, payload) {{
  try {{
    const p = payload ?? {{}};
    const body = {{
      id: (globalThis.crypto?.randomUUID?.() ?? `${{Date.now()}}-${{Math.random()}}`),
      agent: "opencode",
      type,
      session_id: p.sessionID ?? "",
      cwd: p.cwd ?? "",
      message: p.message ?? "",
      is_subagent: p.is_subagent === true,
      timestamp: Date.now(),
    }};
    if (p.tool_name) body.tool_name = p.tool_name;
    const options = {{
      method: "POST",
      headers: {{ "content-type": "application/json", "x-bark-token": TOKEN }},
      body: JSON.stringify(body),
    }};
    // AbortSignal.timeout 需要 Node 17.3+ / 现代运行时；取不到就退回无超时（老版本行为）
    if (typeof AbortSignal !== "undefined" && typeof AbortSignal.timeout === "function") {{
      options.signal = AbortSignal.timeout(POST_TIMEOUT_MS);
    }}
    await fetch(ENDPOINT, options);
  }} catch {{
    // daemon 未运行 / 超时 / 瞬时失败都静默，绝不阻塞 OpenCode
  }}
}}

// —— 会话级缓存（全部有界，防长期驻留的插件进程内存增长）——
// sessionID → cwd：运行中的事件只带 sessionID，cwd 唯一来源是
// session.created/updated 的 info.directory，不记下来终态/等待通知就没有项目名
const dirs = new Map();
// 子代理会话（session.info.parentID 非空）：其事件打 is_subagent，
// 否则一个任务拆几个子代理就弹几条「任务完成」
const subSessions = new Set();
// 已开档（发出过回合开始心跳）的会话：busy 只在回合开始发一次，
// retry 恢复后的 busy 不重复发，否则回合数虚高
const turnOpen = new Set();
// 已发过执行中心跳的工具部件 id：state 会 pending→running→completed 逐态各推
// 一条事件，不合并的话一次工具调用 tool_calls 就双计
const toolPosted = new Set();
// sessionID → 最近一次中止时刻：压制其后 10s 内的 session.idle
const recentAbort = new Map();
// (事件名, 会话) → 最近一次放行时刻：双通道分发去抖（见 isDuplicateDispatch）
const recentDispatch = new Map();

// permission.updated 的终局状态值：这些是「请求已有结论」的状态变更，
// 不是「发起请求」，不该弹「需要确认」（§2.14b）
const PERMISSION_SETTLED = new Set([
  "approved", "granted", "denied", "rejected", "cancelled", "canceled", "completed", "resolved",
]);

function isSettledPermission(payload) {{
  for (const key of ["status", "state"]) {{
    const v = payload ? payload[key] : undefined;
    if (typeof v === "string" && PERMISSION_SETTLED.has(v.toLowerCase())) return true;
  }}
  return false;
}}

/**
 * (事件名, 会话) 200ms 去抖（§2.14a）：插件同时挂了通用 `event` 回调与逐事件键，
 * 某些版本若双派发，同一事件会被 POST 两次且**每次 id 都是新的**（绕过 daemon 的
 * id 去重）→ 双通知。这里在入口按 (事件名, 会话) 去抖。代价：同一会话 200ms 内的
 * 同名事件只报一条（工具心跳是提示性的，少一条不影响正确性；终态双发才是灾难）。
 */
function isDuplicateDispatch(eventName, sid) {{
  const key = `${{eventName}}\u0000${{sid}}`;
  const now = Date.now();
  const prev = recentDispatch.get(key);
  if (prev !== undefined && now - prev < 200) return true;
  recentDispatch.set(key, now);
  if (recentDispatch.size > 500) {{
    for (const [k, t] of recentDispatch) {{
      if (now - t > 60000) recentDispatch.delete(k);
    }}
    if (recentDispatch.size > 500) recentDispatch.delete(recentDispatch.keys().next().value);
  }}
  return false;
}}

function capBounded(map, max) {{
  if (map.size > max) map.delete(map.keys().next().value);
}}

function rememberSession(info) {{
  if (!info || typeof info.id !== "string" || !info.id) return;
  if (typeof info.directory === "string" && info.directory) {{
    if (dirs.get(info.id) !== info.directory) {{
      dirs.set(info.id, info.directory);
      capBounded(dirs, 200);
    }}
  }}
  if (info.parentID && !subSessions.has(info.id)) {{
    subSessions.add(info.id);
    capBounded(subSessions, 200);
  }}
}}

async function handle(eventName, payload) {{
  const p = payload ?? {{}};
  if (eventName === "session.created" || eventName === "session.updated") {{
    rememberSession(p.info);
  }}
  // sessionID 的位置随事件而异：大多数在顶层；session.created/updated 在 info.id；
  // message.part.updated 的顶层只有 part，ID 在 part.sessionID 里（官方 types.gen.ts）
  const sid = p.sessionID ?? p.info?.id ?? p.part?.sessionID ?? "";
  const cwd = sid ? (dirs.get(sid) ?? "") : "";
  const sub = subSessions.has(sid);
  // 双通道分发去抖（§2.14a）：sid 解析完就判，重复派发直接丢弃
  if (isDuplicateDispatch(eventName, sid)) return;

  // 中止检测：用户 Esc 取消回合时 OpenCode 走 session.error，错误名为
  // MessageAbortedError（社区插件 opencode-auto-resume 以同名错误判定 ESC 取消）。
  // 归一成 run_aborted 而不是 run_failed——自己按的停止不亮终止色、不弹「任务失败」。
  // 判定用防御式字符串匹配（官方事件页未给出 session.error 的载荷 schema）：
  // 匹配不上就按原样走 run_failed，最坏情况 = 旧行为。
  if (eventName === "session.error") {{
    turnOpen.delete(sid);
    if (isAbort(p)) {{
      const now = Date.now();
      if (sid) {{
        recentAbort.set(sid, now);
        for (const [k, t] of recentAbort) {{
          if (now - t > 60000) recentAbort.delete(k);
        }}
      }}
      await post("run_aborted", {{ sessionID: sid, cwd, is_subagent: sub }});
      return;
    }}
    await post("run_failed", {{ sessionID: sid, cwd, is_subagent: sub, message: p.error?.data?.message ?? p.error?.message ?? "" }});
    return;
  }}
  // 中止后的 session.idle 压制掉：回合被取消后会话同样转入空闲，
  // 不压制的话中止（已中止）会紧跟一条绿色「任务完成」，谎报跑完
  if (eventName === "session.idle") {{
    turnOpen.delete(sid);
    if (sid && Date.now() - (recentAbort.get(sid) ?? 0) < 10000) {{
      return;
    }}
    await post("run_completed", {{ sessionID: sid, cwd, is_subagent: sub }});
    return;
  }}
  // 心跳一：session.status busy = 回合开始 →「思考中」。一回合只发一条：
  // retry 恢复后的 busy 不再发；idle 只清回合标记（完成由 session.idle 报告）
  if (eventName === "session.status") {{
    const st = p.status?.type;
    if (st === "idle") {{
      turnOpen.delete(sid);
    }} else if (st === "busy") {{
      if (!turnOpen.has(sid)) {{
        turnOpen.add(sid);
        capBounded(turnOpen, 500);
        await post("activity", {{ sessionID: sid, cwd, is_subagent: sub }});
      }}
    }} else if (st === "retry") {{
      // 模型调用失败重试：不当新回合（无工具心跳会让回合数虚高），也不能完全
      // 静默——长重试会被 daemon 的心跳判死误报「意外终止」。落一条工具级失败
      // （中性色入事件流、会话保持运行中、不通知），回合保持开档
      turnOpen.add(sid);
      await post("tool_failed", {{ sessionID: sid, cwd, is_subagent: sub, message: p.status?.message ?? "模型调用重试中" }});
    }}
    return;
  }}
  // 心跳二：工具部件进入 pending/running →「执行工具」。同一部件只发一条
  if (eventName === "message.part.updated") {{
    const part = p.part ?? {{}};
    if (!part || part.type !== "tool") return;
    const st = part.state?.status;
    // part.id 缺失时**跳过去重**（§2.14d）：旧实现用 part.id 当 Set 键，缺失时
    // 全部坍缩到共享的 undefined 键——同会话后续所有无 id 部件的心跳都被吞掉。
    // 宁可重复发心跳（心跳丢了/重了都无害），不能丢「执行工具」的点亮信号。
    const hasPartId = part.id !== undefined && part.id !== null && part.id !== "";
    if (st === "pending" || st === "running") {{
      if (!hasPartId || !toolPosted.has(part.id)) {{
        if (hasPartId) {{
          toolPosted.add(part.id);
          capBounded(toolPosted, 500);
        }}
        await post("activity", {{ sessionID: sid, cwd, is_subagent: sub, tool_name: part.tool ?? "" }});
      }}
      return;
    }}
    if (hasPartId) toolPosted.delete(part.id);
    if (st === "error") {{
      // 工具级失败 ≠ 回合失败：agent 会自行重试。归一 tool_failed——会话保持
      // 运行中（相位回落思考中）、不通知、不亮终止色，事件中性色入事件流
      await post("tool_failed", {{ sessionID: sid, cwd, is_subagent: sub, tool_name: part.tool ?? "", message: part.state?.error ?? "" }});
    }}
    return;
  }}

  const type = KIND_MAP[eventName];
  if (!type) return;
  // permission.updated 只在「发起请求」时上报（§2.14b）：批准/拒绝等终局状态
  // 变更再弹「需要确认」是纯噪音。payload 没有 status/state 类字段时维持原行为。
  if (type === "permission_required" && isSettledPermission(p)) return;
  await post(type, {{ sessionID: sid, cwd, is_subagent: sub, message: p.info?.title ?? p.title ?? "" }});
}}

function isAbort(payload) {{
  try {{
    const name = payload?.error?.name ?? payload?.name ?? "";
    if (typeof name === "string" && /abort/i.test(name)) return true;
    if (JSON.stringify(payload).includes("MessageAbortedError")) return true;
  }} catch {{}}
  return false;
}}

export const Plugin = async () => ({{
  // 官方形态：所有事件经由通用 event 回调送达
  event: async ({{ event }}) => {{
    if (!event || !event.type) return;
    await handle(event.type, event.properties ?? event);
  }},
  // 兼容形态：部分版本支持按事件名直接挂载
  "session.created": async (input) => handle("session.created", input),
  "permission.updated": async (input) => handle("permission.updated", input),
  "session.status": async (input) => handle("session.status", input),
  "message.part.updated": async (input) => handle("message.part.updated", input),
  "session.idle": async (input) => handle("session.idle", input),
  "session.error": async (input) => handle("session.error", input),
}});
"#
    )
}

impl OpenCodeAdapter {
    /// plugin 数组里的条目是否指向我们的插件。
    /// 精确判定（旧实现用 contains("opencode-plugin.js") 子串匹配，
    /// 会把用户自己的同名插件条目误认成我们的）：
    /// 路径统一为正斜杠后，必须**等于当前 plugin_file()**，或者
    /// 「父目录恰好名为 agent-bark 且文件名恰好为 opencode-plugin.js」
    /// （兼容配置目录迁移后遗留的旧绝对路径）。
    /// 形状相同还要**验生成标记**（§2.14c）：目标文件存在且可读、却**不含**
    /// "Generated by agent-bark" 时判为用户自己的同形插件——不认领它，
    /// register 就不会改写它、unregister 不会删除它。文件缺失/不可读维持现判
    /// （认领）：那是「我们生成的插件被删了/旧路径失效」的场景，修复与回收路径
    /// 必须还能找到它。
    fn entry_matches(v: &Value) -> bool {
        let Some(s) = v.as_str() else { return false };
        let s_norm = s.replace('\\', "/");
        let shape_ok = if s_norm == plugin_path_str() {
            true
        } else {
            let mut parts = s_norm.rsplit('/');
            let file_ok = parts.next().is_some_and(|f| f == "opencode-plugin.js");
            let dir_ok = parts.next().is_some_and(|d| d == "agent-bark");
            file_ok && dir_ok
        };
        if !shape_ok {
            return false;
        }
        match std::fs::read_to_string(Path::new(s)) {
            Ok(content) if !content.contains("Generated by agent-bark") => false,
            _ => true,
        }
    }

    /// 条目是否恰好等于当前插件路径（verify 用：旧路径条目算漂移，不算已接入）
    fn entry_is_current(v: &Value) -> bool {
        v.as_str().is_some_and(|s| s.replace('\\', "/") == plugin_path_str())
    }
}

impl HookAdapter for OpenCodeAdapter {
    fn kind(&self) -> AgentKind {
        AgentKind::OpenCode
    }

    fn display_name(&self) -> &'static str {
        AgentKind::OpenCode.display_name()
    }

    fn is_installed(&self) -> bool {
        config_file().parent().is_some_and(|p| p.exists())
    }

    fn is_registered(&self) -> bool {
        if !plugin_file().exists() {
            return false;
        }
        let Ok(doc) = jsonio::read_doc(&config_file()) else {
            return false;
        };
        doc.get("plugin")
            .and_then(|p| p.as_array())
            .is_some_and(|arr| arr.iter().any(Self::entry_matches))
    }

    fn config_paths(&self) -> Vec<PathBuf> {
        vec![config_file(), plugin_file()]
    }

    fn hook_events(&self) -> Vec<&'static str> {
        // 仅文档性（OpenCode 由插件直接 POST，不走 hook 子命令）；
        // 事件名以官方 SDK types.gen.ts 为准
        vec![
            "session.created",
            "session.status",
            "message.part.updated",
            "permission.updated",
            "session.idle",
            "session.error",
        ]
    }

    fn event_kind(&self, _event_name: &str) -> Option<EventKind> {
        // OpenCode 事件由 JS 插件直接归一化后 POST，不经过 hook 子命令
        None
    }

    fn register(&self, ctx: &RegisterCtx) -> anyhow::Result<()> {
        let cfg_path = config_file();
        let parent = cfg_path
            .parent()
            .ok_or_else(|| anyhow::anyhow!("非法路径: {}", cfg_path.display()))?;
        if !parent.exists() {
            anyhow::bail!("未检测到 OpenCode（{} 不存在）", parent.display());
        }

        // 1. 先读并校验 opencode.json：解析失败必须中止，否则会把用户的 opencode.json 清空。
        //    注意顺序——绝不能先写插件文件：配置非法时会在用户机器上留下一个含本地
        //    鉴权 token 的孤儿插件文件（本模块的原则是「解析失败绝不写入」）。
        let existed = cfg_path.exists();
        let mut doc = jsonio::Doc::read(&cfg_path)?;

        // 2. 写插件文件（插件内容含端口与 token）。内容一致就不写，避免启动时的
        //    例行刷新白白换 mtime；不一致才走 jsonio 的原子写
        //    （同目录临时文件→rename，避免半写文件被 OpenCode 加载）。
        let js = plugin_js(ctx.port, &ctx.token);
        if std::fs::read_to_string(plugin_file()).map(|current| current != js).unwrap_or(true) {
            jsonio::write_text_atomic(&plugin_file(), &js)?;
        }

        // 3. 注册到 opencode.json 的 plugin 数组（外科手术式）
        let obj = doc
            .value
            .as_object_mut()
            .expect("read_doc 保证顶层是对象");
        let plugin_path = plugin_path_str();
        let plugins = obj
            .entry("plugin")
            .or_insert_with(|| json!([]))
            .as_array_mut()
            .ok_or_else(|| anyhow::anyhow!("{} 的 plugin 字段不是数组，已中止写入", cfg_path.display()))?;

        // 我们的条目：首个就地修复为当前路径（旧路径条目不能留着，否则新路径永不生效），
        // 其余重复项删除；一个都没有才追加
        let mut found = false;
        // 清理时只删我们造的 null 哨兵；用户数组里合法的 null 元素原样保留
        let pre_nulls: Vec<bool> = plugins.iter().map(|v| v.is_null()).collect();
        for v in plugins.iter_mut() {
            if !Self::entry_matches(v) {
                continue;
            }
            if found {
                *v = json!(null); // 重复项，标记删除
            } else {
                found = true;
                if !Self::entry_is_current(v) {
                    *v = json!(plugin_path.as_str());
                }
            }
        }
        if found {
            let mut i = 0usize;
            plugins.retain(|v| {
                let ours = v.is_null() && !pre_nulls.get(i).copied().unwrap_or(true);
                i += 1;
                !ours
            });
        } else {
            plugins.push(json!(plugin_path));
        }
        // 幂等：内容一致则不写（与读取底稿比较，不重读文件）
        let after = serde_json::to_string_pretty(&doc.value)? + "\n";
        if !existed || doc.raw() != after {
            if existed {
                jsonio::backup_once(&cfg_path);
            }
            // Doc::write 自带 CAS：文件被并发修改时报错而非覆盖
            jsonio::Doc::write(doc, &cfg_path)?;
        }
        Ok(())
    }

    fn unregister(&self, ctx: &mut InstallCtx) -> anyhow::Result<()> {
        let cfg_path = config_file();
        if cfg_path.exists() {
            if let Ok(doc) = jsonio::Doc::read(&cfg_path) {
                let mut doc = doc;
                if let Some(plugins) = doc.value.get_mut("plugin").and_then(|p| p.as_array_mut()) {
                    let before = plugins.len();
                    plugins.retain(|v| !Self::entry_matches(v));
                    // 尊重 ctx 语义：dry_run 只计算不落盘；backup=false 时不备份
                    if plugins.len() != before && !ctx.dry_run {
                        if ctx.backup {
                            jsonio::backup_once(&cfg_path);
                        }
                        jsonio::Doc::write(doc, &cfg_path)?;
                    }
                }
            }
        }
        if !ctx.dry_run {
            let _ = std::fs::remove_file(plugin_file());
        }
        Ok(())
    }

    fn verify(&self, _ctx: &RegisterCtx) -> VerifyReport {
        if !config_file().exists() {
            return VerifyReport::NotRegistered;
        }
        match jsonio::read_doc(&config_file()) {
            Err(e) => VerifyReport::ConfigUnreadable {
                path: config_file(),
                reason: e.to_string(),
            },
            Ok(doc) => {
                let plugins = doc.get("plugin").and_then(|p| p.as_array());
                // 必须是「值等于当前 plugin_file()」的条目且插件文件存在才算 Ok：
                // 旧实现只查子串匹配，旧路径条目会误报 Ok
                let current = plugins.is_some_and(|arr| arr.iter().any(Self::entry_is_current));
                if current {
                    return if plugin_file().exists() {
                        VerifyReport::Ok
                    } else {
                        // 登记了但插件文件丢了
                        VerifyReport::NotRegistered
                    };
                }
                if plugins.is_some_and(|arr| arr.iter().any(Self::entry_matches)) {
                    // 只有旧路径条目 → 路径漂移，重新 register 可就地修复
                    return VerifyReport::StalePath { path: config_file() };
                }
                VerifyReport::NotRegistered
            }
        }
    }

    fn normalize(&self, _event_name: &str, _raw: &Value) -> Option<NormalizedEvent> {
        None
    }

    fn unregister_hint(&self) -> Option<&'static str> {
        Some("已移除 opencode.json 里的登记与插件文件；正在运行的 OpenCode 进程里插件仍在内存中，会继续发送事件直到重启它。重启前 daemon 已按开关忽略 OpenCode 的通知")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_plugin_uses_event_callback() {
        let js = plugin_js(1234, "tok");
        assert!(js.contains("event: async ({ event })"), "必须使用官方 event 回调形态");
        assert!(js.contains("\"session.idle\": \"run_completed\"") || js.contains("run_completed"));
        assert!(js.contains("x-bark-token"));
        assert!(js.contains("const TOKEN = \"tok\";"));
    }

    #[test]
    fn generated_plugin_posts_heartbeat() {
        // 没有心跳映射，会话就进不了「运行中」表——旧版只映射终态/打断，
        // 用户看到的就是「跑的时候毫无表现，完成才弹一条通知」
        let js = plugin_js(1234, "tok");
        assert!(js.contains("\"activity\""), "回合开始必须有 activity 心跳（思考中）");
        assert!(js.contains("session.status"), "必须消费 session.status（busy/retry/idle）");
        assert!(js.contains("message.part.updated"), "必须消费 message.part.updated（执行工具）");
        assert!(js.contains("tool_name"), "工具心跳必须带 tool_name（区分思考中/执行工具）");
        assert!(js.contains("tool_failed"), "工具级失败/模型重试归一 tool_failed，不是回合失败");
        assert!(js.contains("turnOpen"), "busy 必须按回合去重（retry 恢复不重复计回合）");
        assert!(js.contains("toolPosted"), "工具部件心跳必须按部件去重（tool_calls 防双计）");
    }

    #[test]
    fn generated_plugin_uses_real_event_names() {
        // 对照官方 SDK types.gen.ts：permission.asked / question.asked 不存在。
        // 断言带引号的事件名字面量（注释里的解释性文字不带引号）
        let js = plugin_js(1234, "tok");
        assert!(js.contains("\"permission.updated\""), "权限打断走 permission.updated");
        assert!(!js.contains("\"permission.asked\""), "permission.asked 不是真实事件名");
        assert!(!js.contains("\"question.asked\""), "opencode 没有 question.asked 事件");
    }

    #[test]
    fn generated_plugin_remembers_session_metadata() {
        // 运行中的事件只带 sessionID：cwd / 子代理标记只能从 session.created/updated
        // 的 info 里记下来，否则通知没有项目名、子代理会话刷屏
        let js = plugin_js(1234, "tok");
        assert!(js.contains("info.directory"), "必须记住会话 cwd");
        assert!(js.contains("parentID"), "子代理会话必须打 is_subagent 标记");
        assert!(js.contains("is_subagent"));
    }

    #[test]
    fn generated_plugin_detects_abort() {
        // 中止链路：session.error(MessageAbortedError) → run_aborted（不亮终止色），
        // 其后的 session.idle 在 10s 内压制（否则中止会紧跟一条绿色「完成」）
        let js = plugin_js(1234, "tok");
        assert!(js.contains("MessageAbortedError"), "中止判定必须覆盖 MessageAbortedError");
        assert!(js.contains("recentAbort"), "必须记录中止时刻以压制随后的 idle");
        assert!(js.contains("run_aborted"), "中止必须归一为 run_aborted");
    }

    #[test]
    fn token_is_js_escaped() {
        // token 含引号/反斜杠时，生成的 JS 字符串字面量必须仍然合法
        let js = plugin_js(1, "a\"b\\c");
        assert!(js.contains("const TOKEN = \"a\\\"b\\\\c\";"), "token 必须转义: {js}");
    }

    #[test]
    fn entry_matching() {
        // 当前路径（正/反斜杠形态都算）
        assert!(OpenCodeAdapter::entry_matches(&json!(plugin_path_str())));
        // 旧版本/跨机迁移写入的等效路径
        assert!(OpenCodeAdapter::entry_matches(&json!("/x/agent-bark/opencode-plugin.js")));
        // 子串相似但不是我们的插件 → 不能误伤
        assert!(!OpenCodeAdapter::entry_matches(&json!("agent-bark-fork/opencode-plugin.js")));
        assert!(!OpenCodeAdapter::entry_matches(&json!("/x/agent-bark/opencode-plugin.js.bak")));
        assert!(!OpenCodeAdapter::entry_matches(&json!("superpowers@git+https://x/y.git")));
    }

    // ---- §1.10 / §2.14 生成插件回归 ------------------------------------------

    /// §1.10：fetch 必须带超时（AbortSignal.timeout + typeof 兜底，与 dsh 同款）——
    /// daemon 端口被「只 accept 不响应」的进程占用时插件回调不得永久挂起
    #[test]
    fn generated_plugin_fetch_has_timeout() {
        let js = plugin_js(1234, "tok");
        assert!(
            js.contains("AbortSignal.timeout(POST_TIMEOUT_MS)"),
            "fetch 必须带 AbortSignal 超时: {js}"
        );
        assert!(js.contains("const POST_TIMEOUT_MS = 2000;"), "常量命名/取值与 dsh 插件一致");
        assert!(
            js.contains("typeof AbortSignal !== \"undefined\""),
            "老运行时取不到 AbortSignal.timeout 时要退回无超时而不是直接崩"
        );
    }

    /// §2.14a：(eventName, sid) 200ms 去抖——通用 event 回调与逐事件键双派发时
    /// 同一事件 POST 两次且每次 id 都是新的，绕过 daemon 去重 → 双通知
    #[test]
    fn generated_plugin_dedupes_dual_channel_dispatch() {
        let js = plugin_js(1234, "tok");
        assert!(js.contains("function isDuplicateDispatch(eventName, sid)"), "{js}");
        assert!(js.contains("recentDispatch"), "去抖要有按 (事件名, 会话) 的时间戳表");
        assert!(js.contains("now - prev < 200"), "去抖窗 200ms");
        // 去抖必须在 handle 入口（sid 解析后）生效，而不是只挡某一条通道
        let handle_body = js.split("async function handle(eventName, payload)").nth(1).unwrap_or("");
        let head = handle_body.split("session.error").next().unwrap_or("");
        assert!(head.contains("isDuplicateDispatch(eventName, sid)"), "去抖要在 handle 入口: {head}");
    }

    /// §2.14b：permission.updated 带终局 status/state（approved/granted/denied/…）
    /// 时不映射——批准/拒绝后的状态变更不该再弹「需要确认」
    #[test]
    fn generated_plugin_ignores_settled_permission_updates() {
        let js = plugin_js(1234, "tok");
        assert!(js.contains("function isSettledPermission(payload)"), "{js}");
        for v in ["approved", "granted", "denied", "rejected", "cancelled", "canceled", "completed", "resolved"] {
            assert!(js.contains(&format!("\"{v}\"")), "终局状态表缺 {v}");
        }
        assert!(js.contains("for (const key of [\"status\", \"state\"])"), "两类状态字段都要看");
        assert!(
            js.contains("if (type === \"permission_required\" && isSettledPermission(p)) return;"),
            "映射前必须过滤终局状态变更"
        );
    }

    /// §2.14d：part.id 缺失时跳过去重（不能坍缩到共享 undefined 键）
    #[test]
    fn generated_plugin_tool_dedupe_requires_part_id() {
        let js = plugin_js(1234, "tok");
        assert!(js.contains("const hasPartId = part.id !== undefined && part.id !== null && part.id !== \"\";"), "{js}");
        assert!(
            js.contains("if (!hasPartId || !toolPosted.has(part.id))"),
            "无 id 部件不去重（宁可重复心跳，不能丢点亮信号）"
        );
        assert!(js.contains("if (hasPartId) toolPosted.delete(part.id);"), "无 id 时不按 undefined 键清理");
    }

    /// §2.14c：形状匹配但文件**可读且不含生成标记** → 判为用户同形插件，不认领
    #[test]
    fn entry_matches_respects_generated_marker() {
        let dir = std::env::temp_dir().join(format!("agent-bark-oc-{}", uuid::Uuid::new_v4().simple()));
        let ours_dir = dir.join("agent-bark");
        std::fs::create_dir_all(&ours_dir).unwrap();
        let file = ours_dir.join("opencode-plugin.js");
        let entry = json!(file.to_string_lossy().replace('/', "\\"));

        // 含生成标记 → 认领
        std::fs::write(&file, "// Generated by agent-bark. Do not edit.\n").unwrap();
        assert!(OpenCodeAdapter::entry_matches(&entry), "含标记的同形文件是我们的");

        // 用户自己的同形插件（可读、无标记）→ 不认领：register 不得改写它、
        // unregister 不得删除它
        std::fs::write(&file, "// my own opencode plugin\nexport const Plugin = () => ({});\n").unwrap();
        assert!(
            !OpenCodeAdapter::entry_matches(&entry),
            "无生成标记的同形文件是用户的，绝不能认领"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    /// §2.14a：去抖键含事件名与会话 id，且时间戳表有界（防长期驻留内存增长）
    #[test]
    fn generated_plugin_dedup_key_and_bounds() {
        let js = plugin_js(1234, "tok");
        assert!(
            js.contains("${eventName}\u{5c}u0000${sid}") || js.contains("recentDispatch"),
            "去抖键必须由 (事件名, 会话) 组成"
        );
        assert!(js.contains("recentDispatch.size > 500"), "去抖表必须有上限");
        assert!(js.contains("now - t > 60000"), "过期的去抖项要清理");
    }

    /// §2.14b：状态值比较大小写不敏感（不同版本的取值大小写可能不同）
    #[test]
    fn generated_plugin_permission_status_check_is_case_insensitive() {
        let js = plugin_js(1234, "tok");
        assert!(
            js.contains("PERMISSION_SETTLED.has(v.toLowerCase())"),
            "状态值比较必须大小写不敏感: {js}"
        );
    }

    /// §4.14（顺手修）：id 回退要带随机熵——`String(Date.now())` 同毫秒双投递
    /// 会撞 id 被 daemon 去重误杀
    #[test]
    fn generated_plugin_id_fallback_has_entropy() {
        let js = plugin_js(1234, "tok");
        assert!(
            js.contains("globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random()}`"),
            "id 回退必须含 Math.random() 熵: {js}"
        );
        assert!(!js.contains("String(Date.now())"), "同毫秒碰撞的旧回退不得回来");
    }

    /// §2.14c：形状不对（哪怕文件里有生成标记）也不认领
    #[test]
    fn entry_matches_rejects_other_shapes_even_with_marker() {
        let dir = std::env::temp_dir().join(format!("agent-bark-oc3-{}", uuid::Uuid::new_v4().simple()));
        std::fs::create_dir_all(&dir).unwrap();
        let other = dir.join("mytools").join("opencode-plugin.js");
        std::fs::create_dir_all(other.parent().unwrap()).unwrap();
        std::fs::write(&other, "// Generated by agent-bark\n").unwrap();
        let entry = json!(other.to_string_lossy());
        assert!(
            !OpenCodeAdapter::entry_matches(&entry),
            "父目录不叫 agent-bark 的同名文件不是我们的"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    /// §2.14c：文件缺失/不可读维持现判（认领）——旧路径/被删的我们插件要能被
    /// 修复与回收找到
    #[test]
    fn entry_matches_missing_file_still_claimed() {
        let dir = std::env::temp_dir().join(format!("agent-bark-oc2-{}", uuid::Uuid::new_v4().simple()));
        let ours_dir = dir.join("agent-bark");
        std::fs::create_dir_all(&ours_dir).unwrap();
        let file = ours_dir.join("opencode-plugin.js");
        let entry = json!(file.to_string_lossy().replace('/', "\\"));

        assert!(OpenCodeAdapter::entry_matches(&entry), "文件缺失时维持现判（认领以便回收/修复）");
        // 可读且含标记 → 认领（可读但**无**标记 → 判给用户，见上一条测试）
        std::fs::write(&file, "// Generated by agent-bark. Do not edit.\n").unwrap();
        assert!(OpenCodeAdapter::entry_matches(&entry), "可读 + 含标记 → 认领");
        let _ = std::fs::remove_dir_all(&dir);
    }
}
